ARG GEONODE_IMAGE_VERSION
FROM zalf/geonode-base:${GEONODE_IMAGE_VERSION}

# geonode-project installs ldap per default
# there the locale is set explicitly
# see https://github.com/GeoNode/geonode-project/blob/master/Dockerfile#L8C1-L11C17
RUN sed -i -e 's/# C.UTF-8 UTF-8/C.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# copy agrovoc importer scripts
COPY ./geonode/apps/geonode-agrovoc-importer/load_agrovoc_thesaurus.py /usr/src/geonode/geonode/base/management/commands/
COPY ./geonode/apps/geonode-agrovoc-importer/load_gemet_thesaurus.py /usr/src/geonode/geonode/base/management/commands/

# import additional requirements into image
COPY docker/geonode/requirements-production.txt /usr/src/geonode/requirements-production.txt
RUN yes w | pip install --src /usr/src -r /usr/src/geonode/requirements-production.txt

RUN rm .env*
